# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
repos:
  MRAN: "https://mran.microsoft.com/snapshot/2017-07-20"
addons:
  apt:
    packages:
      - libudunits2-dev

script:
  - Rscript -e "devtools::install()"
  - Rscript -e "rmarkdown::render('analysis/paper.Rmd')"

warnings_are_errors: false
