# Build our Docker container and R pkg on Travis

env:
  global:
  - REPO=benmarwick/rrtools

sudo: required

warnings_are_errors: false

language: generic

services:
  - docker

before_install:
    # create & run container using our dockerfile, i.e. compile pkg and render Rmd to Word doc
  - docker build -t $REPO .

# push our custom docker container to docker hub, env vars stored on travis-ci.org
after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=benmarwick/rrtools
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
