# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# set pkg repo for the versioned CRAN hosted by Microsoft
repos:
  MRAN: "https://mran.microsoft.com/snapshot/2017-09-06"

# install linux libraries that some R pkgs depend on, add more as needed
addons:
  apt:
    packages:
      - libudunits2-dev

script:
    # build and install custom library with custom functions
  - Rscript -e "devtools::install()"
    # render the main mansucript document into HTML/Word/PDF as specified in the Rmd
    # you may need to edit the path and file name to point to the Rmd file to render
  - R -e "rmarkdown::render('/rrtools/analysis/paper/paper.Rmd')"

# be more tolerant :)
warnings_are_errors: false
